version: '3'
services:
  fastapi-app:
    build: .
    volumes:
      - .dockervenv:/src/.venv
      # - .:/src
    ports:
      - 8000:8000
    environment:
      - WATCHFILES_FORCE_POLLING=true # for hot reload
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'demo'
      TZ: 'Asia/Seoul'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password # MySQL 8.0 default value : "caching_sha2_password"
    ports:
      - 33306:3306
    healthcheck:
      test: ["CMD", "/usr/bin/mysql", "$MYSQL_DATABASE"]
      # test: ["CMD", "/usr/bin/mysql", "--user=root", "--password=rootpassword", "$MYSQL_DATABASE"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
volumes:
  mysql_data: